### ISSUE TITLE
Add CityLab

### ISSUE THREAD

**Issue by wolframalexa** [loganmeetsworld/awesome-newsroom-tech#3]
Website: citylab.com
Uses data visualization to tell the story of urban spaces and transit

**Comment by loganmeetsworld** [comment]
Added in https://github.com/loganmeetsworld/awesome-newsroom-tech/commit/5233aa746374ab40e6ed5e4a37a66012b8932acd

Might moved as a "project" under The Atlantic, but keeping for now. Thank you for opening an issue!
