### ISSUE TITLE
Add The Pudding

### ISSUE THREAD

**Issue by simonft** [loganmeetsworld/awesome-newsroom-tech#7]
Github: https://github.com/the-pudding/
Website: https://pudding.cool/

**projects:**
General data:
https://github.com/the-pudding/data

Source code for https://pudding.cool/2019/09/millennials/
https://github.com/the-pudding/millennial_killers

They also have a "how" section of articles:
 https://pudding.cool/topics/#how

**Comment by loganmeetsworld** [comment]
added in 85e0fd1
